"""Reviewed Phase00 native acceptance procedure catalog.

This module is a controller specification, not evidence that any case ran. Every
procedure uses fixed preparation/action/oracle enums; arbitrary shell commands,
caller-provided expected results and fixture flags are forbidden. Runtime case
closure still requires registered native LAB/SITE execution plus journal/evidence
oracles in harness_controller.py.
"""
from dataclasses import dataclass
from ..codec import digest
from ..errors import require

ENVIRONMENTS=frozenset({'DOCUMENT','LAB','LAB_SITE'})
ROUTES=frozenset({'PASSIVE','DISCOVERY','ENGINE','CREATE','ADOPT','RESTORE_EXPORT',
 'RESTORE_IMPORT','SITE_VERIFY','TARGET_LIFECYCLE','HOST_RESTART','RESTORE_VERIFY',
 'RECONCILIATION_ONLY','SUPPORT_BUNDLE','ENTRY_ONLY'})
PREPARATIONS=frozenset({
 'EXACT_REVIEW_SET','MATCHING_PROFILE','PROFILE_MISMATCH','RESOURCE_BOUNDARY_MATRIX',
 'NETWORK_CONTEXT_MATRIX','STANDARD_LIFECYCLE','STAGED_CONFIG_INACTIVE','NETWORK_BOUNDARY_CHANGE',
 'PLANNED_ENGINE_TRANSITION','MISSED_EPOCH_WITNESS','STALE_TERMINAL_CLOCK','STOPPED_TARGET',
 'ACTIVE_GUARD_HOLDER','CROSS_SCOPE_HOLDER','SHARED_VOLUME_PRESSURE','CROSS_SID_HOLDER',
 'NATIVE_TIMEOUT','ABANDONED_GUARD','POST_REGISTRATION_CRASH','SOURCE_DESTINATION_RESTORE',
 'JOURNAL_WRITE_FAILURE','BUNDLE_COMPLETE','OPTIONAL_COLLECTOR_FAILURE','MANDATORY_COLLECTOR_FAILURE',
 'OPTIONAL_CAP','MANDATORY_CAP','NESTED_SECRET_CANARY','REDACTION_RESIDUAL','MULTI_FAILURE_PRIVACY',
 'BUNDLE_HASH_TAMPER','OUTPUT_PUBLISH_FAILURE','PRECREATE_INVENTORY','FAILED_RUN_EVIDENCE',
 'PATH_ESCAPE','GATE_ASSESSMENT_BOUNDARY','CLEAN_RESTORE_SOURCE','ADOPT_RESTORE_SOURCE',
 'ISOLATION_MISSING','SYNTHETIC_ISOLATION_CANARY','ISOLATION_DRIFT','SAME_HOST_DIRTY',
 'SENSITIVE_SOURCE','CHECKPOINT_TAMPER','RETAINED_CAPACITY_PRESSURE','VERIFY_MUTATION_REQUEST',
 'COEXISTING_RESOURCE','CREATE_CLEAN_HOST','ADOPT_ELIGIBLE','ENGINE_CLEAN_HOST','PROTECTION_MISSING',
 'RECOVERY_DEPENDS_ON_SOURCE','CONSISTENCY_BOUNDARY_DRIFT','C3_CRASH','OWNER_POSTCHECK_MISSING',
 'EXISTING_TARGET_PROTECTION','QUALIFICATION_MISSING','QUALIFICATION_INVALID','QUALIFICATION_MISMATCH',
 'TRUST_FORGERY','REGISTERED_DISPOSABLE_LAB','SITE_FAKE_LAB','DISCOVERY_UNKNOWN_GUEST',
 'ENGINE_ABSENT_PROFILE','APPROVAL_EXPIRES_ON_RESUME','VIRTUALIZATION_BLOCKED','WRONG_ACTOR',
 'COLLISION_OR_PATH_ATTACK','UNSUPPORTED_PROFILE','RESOURCE_FLOOR_FAILURE','NETWORK_FAILURE',
 'TRUST_FAILURE','MATERIAL_DRIFT','CONCURRENCY_OR_CRASH','REBOOT_OOBE_WAIT','C3_PROTECTION_FAILURE',
 'RESTORE_FAILURE','EVIDENCE_FAILURE','PASSIVE_UNKNOWN_GUEST','GLOBAL_POLICY_DRIFT','JOURNAL_IO_FAILURE'})
ACTIONS=frozenset({'REVIEW_EXACT_CONTENT','INVOKE_PRODUCTION_REQUEST','INVOKE_CONTENDER',
 'RESUME_OR_RECONCILE','RUN_TERMINAL_SWEEP','RUN_SUPPORT_BUNDLE','RUN_RESTORE_SEQUENCE',
 'RUN_OWNER_LIFECYCLE','OBSERVE_ONLY','VERIFY_ENTRY_REJECTION','VERIFY_EVIDENCE_OUTPUT',
 'VERIFY_ISOLATION','VERIFY_PROTECTION','VERIFY_CONCURRENCY_TRACE','VERIFY_NO_MUTATION'})
ORACLES=frozenset({'EXACT_CONTENT_IDENTITY','IDENTITY_PROFILE','RESOURCE_CAPACITY','NETWORK_MATRIX',
 'LIFECYCLE_EPOCH','PASSIVE_NO_LAUNCH','JOURNAL_NO_OVERLAP','BUNDLE_OUTCOME','RESTORE_CONTENT',
 'COEXISTENCE_HEALTH','CREATE_ROUTE','ADOPT_ROUTE','C3_PROTECTION','ENTRY_GATE',
 'EXPECTED_REJECTION','DURABLE_WAIT','UNCERTAIN_RETAINED','RECONCILIATION_ONLY','NO_DUPLICATE_MUTATION',
 'PRIVACY_NO_OUTPUT','OUTPUT_INTEGRITY','OUTPUT_RECOVERY','EVIDENCE_REQUIREDNESS','ISOLATION_BOUNDARY',
 'CHECKPOINT_INTEGRITY','CAPACITY_REMEASURE','PURPOSE_SEPARATION','TERMINAL_FRESHNESS','NO_POLICY_WEAKENING',
 'QUALIFICATION_SCOPE','NO_PROCESS_EXIT_PROOF','PROTECTED_EVIDENCE','VERIFY_NO_MUTATION','COEXISTENCE_HEALTH'})

@dataclass(frozen=True)
class NativeCaseProcedure:
    case_id:str
    environment:str
    preparations:tuple[str,...]
    routes:tuple[str,...]
    controller_steps:tuple[str,...]
    expected_exits:tuple[int,...]
    oracles:tuple[str,...]
    required_evidence:tuple[str,...]
    destructive:bool=False
    actual_native_required:bool=True

    def document(self):
        return {'case_id':self.case_id,'environment':self.environment,
            'preparations':list(self.preparations),'routes':list(self.routes),
            'controller_steps':list(self.controller_steps),'expected_exits':list(self.expected_exits),
            'oracles':list(self.oracles),'required_evidence':list(self.required_evidence),
            'destructive':self.destructive,'actual_native_required':self.actual_native_required}
    @property
    def procedure_digest(self):return digest(self.document())


def P(case,env,prep,routes,steps,exits,oracles,evidence,*,destructive=False,native=True):
    p=NativeCaseProcedure(case,env,tuple(prep),tuple(routes),tuple(steps),tuple(exits),tuple(oracles),tuple(evidence),destructive,native)
    validate_procedure(p);return p


def validate_procedure(p):
    require(p.environment in ENVIRONMENTS and p.preparations and set(p.preparations)<=PREPARATIONS,10,'HARNESS_PROCEDURE_PREP')
    require(p.routes and set(p.routes)<=ROUTES and p.controller_steps and set(p.controller_steps)<=ACTIONS,10,'HARNESS_PROCEDURE_ACTION')
    require(p.expected_exits and all(type(x) is int and x in (0,2,10,11,12,13,14,15,16,17,18,19,20,21,22,23) for x in p.expected_exits),10,'HARNESS_PROCEDURE_EXIT')
    require(p.oracles and set(p.oracles)<=ORACLES and p.required_evidence,10,'HARNESS_PROCEDURE_ORACLE')
    require(not p.destructive or p.environment=='LAB',12,'DESTRUCTIVE_LAB_ONLY')
    return p

# Explicit reviewed mapping. Parent T/F IDs describe matrix procedures; subcases
# are exact single-condition procedures from Acceptance V2.
_ROWS=[
('T00-01','DOCUMENT',['EXACT_REVIEW_SET'],['ENTRY_ONLY'],['REVIEW_EXACT_CONTENT'],[0],['EXACT_CONTENT_IDENTITY'],['E00-10'],False,False),
('T00-02','LAB_SITE',['MATCHING_PROFILE'],['SITE_VERIFY'],['INVOKE_PRODUCTION_REQUEST','RUN_TERMINAL_SWEEP'],[0,11,16,19],['IDENTITY_PROFILE','TERMINAL_FRESHNESS'],['E00-01','E00-02','E00-04','E00-07','E00-14'],False,True),
('T00-03','LAB_SITE',['RESOURCE_BOUNDARY_MATRIX'],['CREATE'],['INVOKE_PRODUCTION_REQUEST'],[0,13,21],['RESOURCE_CAPACITY','JOURNAL_NO_OVERLAP'],['E00-06','E00-11'],False,True),
('T00-04','LAB_SITE',['NETWORK_CONTEXT_MATRIX'],['SITE_VERIFY'],['INVOKE_PRODUCTION_REQUEST','RUN_TERMINAL_SWEEP'],[0,14,19],['NETWORK_MATRIX','NO_POLICY_WEAKENING'],['E00-08','E00-14'],False,True),
('T00-05','LAB_SITE',['STANDARD_LIFECYCLE'],['TARGET_LIFECYCLE','HOST_RESTART','SITE_VERIFY'],['RUN_OWNER_LIFECYCLE','RUN_TERMINAL_SWEEP'],[0,19,20],['LIFECYCLE_EPOCH','C3_PROTECTION','TERMINAL_FRESHNESS'],['E00-09','E00-12','E00-14'],False,True),
('T00-06','LAB_SITE',['STOPPED_TARGET'],['PASSIVE','DISCOVERY'],['OBSERVE_ONLY','INVOKE_PRODUCTION_REQUEST'],[0,10,20],['PASSIVE_NO_LAUNCH','EXACT_CONTENT_IDENTITY'],['E00-01','E00-10','E00-11'],False,True),
('T00-07','LAB',['ACTIVE_GUARD_HOLDER'],['CREATE','RECONCILIATION_ONLY'],['INVOKE_CONTENDER','RESUME_OR_RECONCILE','VERIFY_CONCURRENCY_TRACE'],[0,17,18,20,21],['JOURNAL_NO_OVERLAP','UNCERTAIN_RETAINED','NO_DUPLICATE_MUTATION'],['E00-11'],True,True),
('T00-08','LAB',['BUNDLE_COMPLETE'],['SUPPORT_BUNDLE'],['RUN_SUPPORT_BUNDLE','VERIFY_EVIDENCE_OUTPUT'],[0,2,15,18,22,23],['BUNDLE_OUTCOME','EVIDENCE_REQUIREDNESS','PRIVACY_NO_OUTPUT'],['E00-16','E00-17'],False,True),
('T00-09','LAB_SITE',['CLEAN_RESTORE_SOURCE'],['RESTORE_EXPORT','RESTORE_IMPORT','RESTORE_VERIFY'],['RUN_RESTORE_SEQUENCE'],[0,11,12,13,15,16,19],['RESTORE_CONTENT','ISOLATION_BOUNDARY','CHECKPOINT_INTEGRITY'],['E00-09','E00-15'],False,True),
('T00-10','LAB_SITE',['COEXISTING_RESOURCE'],['HOST_RESTART','SITE_VERIFY'],['RUN_OWNER_LIFECYCLE','RUN_TERMINAL_SWEEP'],[0,19,20],['COEXISTENCE_HEALTH','C3_PROTECTION'],['E00-12','E00-14'],False,True),
('T00-11','LAB_SITE',['CREATE_CLEAN_HOST'],['CREATE'],['INVOKE_PRODUCTION_REQUEST'],[0,10,16,20],['CREATE_ROUTE','NO_DUPLICATE_MUTATION'],['E00-03','E00-04','E00-09','E00-11'],False,True),
('T00-12','LAB_SITE',['ADOPT_ELIGIBLE'],['ADOPT'],['INVOKE_PRODUCTION_REQUEST'],[0,11,12],['ADOPT_ROUTE','RESTORE_CONTENT'],['E00-03','E00-04','E00-09'],False,True),
('T00-13','LAB',['ENGINE_CLEAN_HOST'],['ENGINE','RECONCILIATION_ONLY'],['VERIFY_PROTECTION','INVOKE_PRODUCTION_REQUEST','RESUME_OR_RECONCILE'],[0,11,12,15,16,19,20],['C3_PROTECTION','DURABLE_WAIT','RECONCILIATION_ONLY'],['E00-12','E00-11'],True,True),
('T00-14','LAB_SITE',['REGISTERED_DISPOSABLE_LAB'],['ENTRY_ONLY','DISCOVERY','ENGINE','CREATE','ADOPT','SITE_VERIFY','RECONCILIATION_ONLY'],['VERIFY_ENTRY_REJECTION','INVOKE_PRODUCTION_REQUEST'],[0,10,11,12,15,16,20],['ENTRY_GATE','QUALIFICATION_SCOPE','EXPECTED_REJECTION'],['E00-10','E00-13'],False,True),
# Mandatory F00 failures
('F00-01','LAB',['VIRTUALIZATION_BLOCKED'],['ENGINE'],['VERIFY_ENTRY_REJECTION'],[11],['EXPECTED_REJECTION','VERIFY_NO_MUTATION'],['E00-02'],False,True),
('F00-02','LAB',['WRONG_ACTOR'],['ENTRY_ONLY'],['VERIFY_ENTRY_REJECTION'],[12],['EXPECTED_REJECTION','QUALIFICATION_SCOPE'],['E00-01','E00-10'],False,True),
('F00-03','LAB',['COLLISION_OR_PATH_ATTACK'],['CREATE'],['VERIFY_ENTRY_REJECTION'],[10,16],['EXPECTED_REJECTION','VERIFY_NO_MUTATION'],['E00-03','E00-11'],False,True),
('F00-04','LAB',['UNSUPPORTED_PROFILE'],['ENTRY_ONLY'],['VERIFY_ENTRY_REJECTION'],[11,16],['EXPECTED_REJECTION','QUALIFICATION_SCOPE'],['E00-01','E00-02','E00-13'],False,True),
('F00-05','LAB',['RESOURCE_FLOOR_FAILURE'],['CREATE'],['VERIFY_ENTRY_REJECTION'],[13,21],['RESOURCE_CAPACITY','EXPECTED_REJECTION'],['E00-06','E00-11'],False,True),
('F00-06','LAB',['NETWORK_FAILURE'],['SITE_VERIFY'],['INVOKE_PRODUCTION_REQUEST','RUN_TERMINAL_SWEEP'],[14,19],['NETWORK_MATRIX','NO_POLICY_WEAKENING'],['E00-08','E00-14'],False,True),
('F00-07','LAB',['TRUST_FAILURE'],['ENTRY_ONLY'],['VERIFY_ENTRY_REJECTION'],[11,15],['ENTRY_GATE','EXPECTED_REJECTION'],['E00-10','E00-13'],False,True),
('F00-08','LAB',['MATERIAL_DRIFT'],['ENTRY_ONLY','SITE_VERIFY'],['VERIFY_ENTRY_REJECTION','RUN_TERMINAL_SWEEP'],[11,16,19],['EXPECTED_REJECTION','TERMINAL_FRESHNESS'],['E00-10','E00-14'],False,True),
('F00-09','LAB',['CONCURRENCY_OR_CRASH'],['CREATE','RECONCILIATION_ONLY'],['INVOKE_CONTENDER','RESUME_OR_RECONCILE','VERIFY_CONCURRENCY_TRACE'],[17,21],['JOURNAL_NO_OVERLAP','UNCERTAIN_RETAINED','RECONCILIATION_ONLY'],['E00-11'],True,True),
('F00-10','LAB',['REBOOT_OOBE_WAIT'],['ENGINE','CREATE','RECONCILIATION_ONLY'],['INVOKE_PRODUCTION_REQUEST','RESUME_OR_RECONCILE'],[17,20],['DURABLE_WAIT','NO_DUPLICATE_MUTATION'],['E00-11','E00-12'],True,True),
('F00-11','LAB',['C3_PROTECTION_FAILURE'],['ENGINE','HOST_RESTART'],['VERIFY_PROTECTION','VERIFY_ENTRY_REJECTION'],[11,12,15,19,20],['C3_PROTECTION','EXPECTED_REJECTION'],['E00-12'],True,True),
('F00-12','LAB',['RESTORE_FAILURE'],['RESTORE_IMPORT','RESTORE_VERIFY'],['RUN_RESTORE_SEQUENCE'],[11,12,15,19],['CHECKPOINT_INTEGRITY','ISOLATION_BOUNDARY','RESTORE_CONTENT'],['E00-15'],True,True),
('F00-13','LAB',['EVIDENCE_FAILURE'],['SUPPORT_BUNDLE'],['RUN_SUPPORT_BUNDLE','VERIFY_EVIDENCE_OUTPUT'],[2,15,18,22,23],['BUNDLE_OUTCOME','PRIVACY_NO_OUTPUT','OUTPUT_RECOVERY'],['E00-16','E00-17'],False,True),
('F00-14','LAB',['PASSIVE_UNKNOWN_GUEST'],['PASSIVE'],['OBSERVE_ONLY'],[0,20],['PASSIVE_NO_LAUNCH','EVIDENCE_REQUIREDNESS'],['E00-04','E00-10'],False,True),
('F00-15','LAB',['GLOBAL_POLICY_DRIFT'],['HOST_RESTART','RESTORE_IMPORT'],['VERIFY_ENTRY_REJECTION','RUN_OWNER_LIFECYCLE'],[11,16,20],['C3_PROTECTION','ISOLATION_BOUNDARY','NO_POLICY_WEAKENING'],['E00-07','E00-12','E00-15'],True,True),
('F00-16','LAB',['JOURNAL_IO_FAILURE'],['CREATE','SUPPORT_BUNDLE','RECONCILIATION_ONLY'],['INVOKE_PRODUCTION_REQUEST','RESUME_OR_RECONCILE'],[16,18],['UNCERTAIN_RETAINED','OUTPUT_RECOVERY','RECONCILIATION_ONLY'],['E00-11','E00-16'],True,True),
# T05 exact subcases
('T05-A','LAB',['STANDARD_LIFECYCLE'],['TARGET_LIFECYCLE','HOST_RESTART','SITE_VERIFY'],['RUN_OWNER_LIFECYCLE','RUN_TERMINAL_SWEEP'],[0],['LIFECYCLE_EPOCH','TERMINAL_FRESHNESS'],['E00-09','E00-14'],True,True),
('T05-B','LAB',['STAGED_CONFIG_INACTIVE'],['HOST_RESTART','SITE_VERIFY'],['RUN_OWNER_LIFECYCLE','RUN_TERMINAL_SWEEP'],[14,19],['LIFECYCLE_EPOCH','NETWORK_MATRIX','TERMINAL_FRESHNESS'],['E00-07','E00-08','E00-14'],True,True),
('T05-C','LAB',['NETWORK_BOUNDARY_CHANGE'],['HOST_RESTART','SITE_VERIFY'],['RUN_OWNER_LIFECYCLE','RUN_TERMINAL_SWEEP'],[14,19],['NETWORK_MATRIX','TERMINAL_FRESHNESS'],['E00-08','E00-14'],True,True),
('T05-D','LAB',['PLANNED_ENGINE_TRANSITION'],['ENGINE','CREATE'],['INVOKE_PRODUCTION_REQUEST'],[0,16,20],['IDENTITY_PROFILE','CREATE_ROUTE'],['E00-02','E00-03','E00-10'],True,True),
('T05-E','LAB',['MISSED_EPOCH_WITNESS'],['SITE_VERIFY'],['RUN_TERMINAL_SWEEP'],[19],['LIFECYCLE_EPOCH','TERMINAL_FRESHNESS'],['E00-14'],True,True),
('T05-F','LAB',['STALE_TERMINAL_CLOCK'],['SITE_VERIFY','SUPPORT_BUNDLE'],['RUN_TERMINAL_SWEEP','RUN_SUPPORT_BUNDLE'],[19,22],['TERMINAL_FRESHNESS','EVIDENCE_REQUIREDNESS'],['E00-14','E00-17'],False,True),
# T07 exact
('T07-A','LAB',['ACTIVE_GUARD_HOLDER'],['CREATE'],['INVOKE_CONTENDER','INVOKE_PRODUCTION_REQUEST'],[0,21],['JOURNAL_NO_OVERLAP','NO_DUPLICATE_MUTATION'],['E00-11'],True,True),
('T07-B','LAB',['CROSS_SCOPE_HOLDER'],['ENGINE','RESTORE_IMPORT','TARGET_LIFECYCLE'],['INVOKE_CONTENDER','VERIFY_CONCURRENCY_TRACE'],[21],['JOURNAL_NO_OVERLAP'],['E00-11'],True,True),
('T07-C','LAB',['CROSS_SCOPE_HOLDER'],['RESTORE_EXPORT','CREATE','SITE_VERIFY','SUPPORT_BUNDLE'],['INVOKE_CONTENDER','VERIFY_CONCURRENCY_TRACE'],[21],['JOURNAL_NO_OVERLAP','EVIDENCE_REQUIREDNESS'],['E00-11'],True,True),
('T07-D','LAB',['SHARED_VOLUME_PRESSURE'],['CREATE'],['INVOKE_CONTENDER','INVOKE_PRODUCTION_REQUEST'],[13,21],['RESOURCE_CAPACITY','JOURNAL_NO_OVERLAP'],['E00-06','E00-11'],True,True),
('T07-E','LAB',['CROSS_SID_HOLDER'],['CREATE'],['INVOKE_CONTENDER','VERIFY_CONCURRENCY_TRACE'],[12,21],['JOURNAL_NO_OVERLAP','QUALIFICATION_SCOPE'],['E00-01','E00-11'],True,True),
('T07-F','LAB',['NATIVE_TIMEOUT'],['RESTORE_IMPORT','RECONCILIATION_ONLY'],['INVOKE_PRODUCTION_REQUEST','INVOKE_CONTENDER','RESUME_OR_RECONCILE'],[17,21],['UNCERTAIN_RETAINED','NO_DUPLICATE_MUTATION'],['E00-11'],True,True),
('T07-G','LAB',['ABANDONED_GUARD'],['RECONCILIATION_ONLY'],['RESUME_OR_RECONCILE'],[0,20,21],['RECONCILIATION_ONLY','UNCERTAIN_RETAINED'],['E00-11'],True,True),
('T07-H','LAB',['POST_REGISTRATION_CRASH'],['CREATE','RECONCILIATION_ONLY'],['RESUME_OR_RECONCILE'],[20,21],['NO_DUPLICATE_MUTATION','RECONCILIATION_ONLY'],['E00-03','E00-11'],True,True),
('T07-I','LAB',['SOURCE_DESTINATION_RESTORE'],['RESTORE_EXPORT','RESTORE_IMPORT'],['RUN_RESTORE_SEQUENCE','VERIFY_CONCURRENCY_TRACE'],[0],['JOURNAL_NO_OVERLAP','CHECKPOINT_INTEGRITY'],['E00-11','E00-15'],False,True),
('T07-J','LAB',['JOURNAL_WRITE_FAILURE'],['CREATE','RECONCILIATION_ONLY'],['INVOKE_PRODUCTION_REQUEST','RESUME_OR_RECONCILE'],[18],['UNCERTAIN_RETAINED','RECONCILIATION_ONLY'],['E00-11'],True,True),
# T08 exact
('T08-A','LAB',['BUNDLE_COMPLETE'],['SUPPORT_BUNDLE'],['RUN_SUPPORT_BUNDLE','VERIFY_EVIDENCE_OUTPUT'],[0],['BUNDLE_OUTCOME','OUTPUT_INTEGRITY'],['E00-16'],False,True),
('T08-B','LAB',['OPTIONAL_COLLECTOR_FAILURE'],['SUPPORT_BUNDLE'],['RUN_SUPPORT_BUNDLE'],[2],['BUNDLE_OUTCOME','EVIDENCE_REQUIREDNESS'],['E00-16'],False,True),
('T08-C','LAB',['MANDATORY_COLLECTOR_FAILURE'],['SUPPORT_BUNDLE'],['RUN_SUPPORT_BUNDLE'],[22],['BUNDLE_OUTCOME','EVIDENCE_REQUIREDNESS'],['E00-16'],False,True),
('T08-D','LAB',['OPTIONAL_CAP'],['SUPPORT_BUNDLE'],['RUN_SUPPORT_BUNDLE'],[2],['BUNDLE_OUTCOME'],['E00-16'],False,True),
('T08-E','LAB',['MANDATORY_CAP'],['SUPPORT_BUNDLE'],['RUN_SUPPORT_BUNDLE'],[0,22],['BUNDLE_OUTCOME','EVIDENCE_REQUIREDNESS'],['E00-16'],False,True),
('T08-F','LAB',['NESTED_SECRET_CANARY'],['SUPPORT_BUNDLE'],['RUN_SUPPORT_BUNDLE','VERIFY_EVIDENCE_OUTPUT'],[0],['PRIVACY_NO_OUTPUT','OUTPUT_INTEGRITY'],['E00-16'],False,True),
('T08-G','LAB',['REDACTION_RESIDUAL'],['SUPPORT_BUNDLE'],['RUN_SUPPORT_BUNDLE'],[23],['PRIVACY_NO_OUTPUT'],['E00-16'],False,True),
('T08-H','LAB',['MULTI_FAILURE_PRIVACY'],['SUPPORT_BUNDLE'],['RUN_SUPPORT_BUNDLE'],[23],['PRIVACY_NO_OUTPUT','EVIDENCE_REQUIREDNESS'],['E00-16'],False,True),
('T08-I','LAB',['BUNDLE_HASH_TAMPER'],['SUPPORT_BUNDLE'],['VERIFY_EVIDENCE_OUTPUT'],[15],['OUTPUT_INTEGRITY'],['E00-16'],False,True),
('T08-J','LAB',['OUTPUT_PUBLISH_FAILURE'],['SUPPORT_BUNDLE','RECONCILIATION_ONLY'],['RUN_SUPPORT_BUNDLE','RESUME_OR_RECONCILE'],[18],['OUTPUT_RECOVERY','PRIVACY_NO_OUTPUT'],['E00-16'],False,True),
('T08-K','LAB',['PRECREATE_INVENTORY'],['SUPPORT_BUNDLE'],['RUN_SUPPORT_BUNDLE'],[0,22],['BUNDLE_OUTCOME','EVIDENCE_REQUIREDNESS'],['E00-04','E00-16'],False,True),
('T08-L','LAB',['FAILED_RUN_EVIDENCE'],['SUPPORT_BUNDLE'],['RUN_SUPPORT_BUNDLE'],[0,2,22],['BUNDLE_OUTCOME','EVIDENCE_REQUIREDNESS'],['E00-16'],False,True),
('T08-M','LAB',['PATH_ESCAPE'],['SUPPORT_BUNDLE'],['VERIFY_ENTRY_REJECTION'],[10,16],['EXPECTED_REJECTION','PRIVACY_NO_OUTPUT'],['E00-16'],False,True),
('T08-N','LAB',['GATE_ASSESSMENT_BOUNDARY'],['SUPPORT_BUNDLE'],['RUN_SUPPORT_BUNDLE','VERIFY_EVIDENCE_OUTPUT'],[0,18,22],['BUNDLE_OUTCOME','OUTPUT_RECOVERY'],['E00-16','E00-17'],False,True),
# T09 exact
('T09-A','LAB',['CLEAN_RESTORE_SOURCE'],['RESTORE_EXPORT','RESTORE_IMPORT','RESTORE_VERIFY'],['RUN_RESTORE_SEQUENCE'],[0],['RESTORE_CONTENT','CHECKPOINT_INTEGRITY'],['E00-09','E00-15'],True,True),
('T09-B','LAB',['ADOPT_RESTORE_SOURCE'],['RESTORE_IMPORT'],['VERIFY_ENTRY_REJECTION','RUN_RESTORE_SEQUENCE'],[0,11],['ISOLATION_BOUNDARY','RESTORE_CONTENT'],['E00-15'],True,True),
('T09-C','LAB',['ISOLATION_MISSING'],['RESTORE_IMPORT'],['VERIFY_ENTRY_REJECTION'],[11,12],['ISOLATION_BOUNDARY','EXPECTED_REJECTION'],['E00-15'],True,True),
('T09-D','LAB',['SYNTHETIC_ISOLATION_CANARY'],['RESTORE_IMPORT','RESTORE_VERIFY'],['RUN_RESTORE_SEQUENCE','VERIFY_ISOLATION'],[0,19],['ISOLATION_BOUNDARY','RESTORE_CONTENT'],['E00-15'],True,True),
('T09-E','LAB',['ISOLATION_DRIFT'],['RESTORE_IMPORT'],['VERIFY_ENTRY_REJECTION'],[16],['ISOLATION_BOUNDARY','EXPECTED_REJECTION'],['E00-15'],True,True),
('T09-F','LAB',['SAME_HOST_DIRTY'],['RESTORE_IMPORT'],['VERIFY_ENTRY_REJECTION'],[11],['ISOLATION_BOUNDARY','EXPECTED_REJECTION'],['E00-15'],True,True),
('T09-G','LAB',['SENSITIVE_SOURCE'],['RESTORE_EXPORT','RESTORE_IMPORT'],['VERIFY_ENTRY_REJECTION'],[11,12],['EXPECTED_REJECTION','VERIFY_NO_MUTATION'],['E00-15'],True,True),
('T09-H','LAB',['CHECKPOINT_TAMPER'],['RESTORE_IMPORT','RESTORE_VERIFY'],['RUN_RESTORE_SEQUENCE'],[11,15,19],['CHECKPOINT_INTEGRITY','RESTORE_CONTENT'],['E00-15'],True,True),
('T09-I','LAB',['RETAINED_CAPACITY_PRESSURE'],['RESTORE_IMPORT','RESTORE_VERIFY'],['RUN_RESTORE_SEQUENCE'],[13,19],['CAPACITY_REMEASURE','RESTORE_CONTENT'],['E00-06','E00-15'],True,True),
('T09-J','LAB',['VERIFY_MUTATION_REQUEST'],['RESTORE_IMPORT'],['VERIFY_ENTRY_REJECTION'],[10,12],['PURPOSE_SEPARATION','VERIFY_NO_MUTATION'],['E00-10'],False,True),
# T13 exact
('T13-A','LAB',['ENGINE_CLEAN_HOST'],['ENGINE'],['VERIFY_PROTECTION','INVOKE_PRODUCTION_REQUEST'],[0,20],['C3_PROTECTION','DURABLE_WAIT'],['E00-12'],True,True),
('T13-B','LAB',['PROTECTION_MISSING'],['ENGINE'],['VERIFY_ENTRY_REJECTION'],[11],['C3_PROTECTION','VERIFY_NO_MUTATION'],['E00-12'],True,True),
('T13-C','LAB',['RECOVERY_DEPENDS_ON_SOURCE'],['ENGINE'],['VERIFY_ENTRY_REJECTION'],[11],['C3_PROTECTION','VERIFY_NO_MUTATION'],['E00-12'],True,True),
('T13-D','LAB',['CONSISTENCY_BOUNDARY_DRIFT'],['ENGINE'],['VERIFY_ENTRY_REJECTION'],[16],['C3_PROTECTION','EXPECTED_REJECTION'],['E00-12'],True,True),
('T13-E','LAB',['C3_CRASH'],['ENGINE','RECONCILIATION_ONLY'],['INVOKE_PRODUCTION_REQUEST','RESUME_OR_RECONCILE'],[17,18,19],['C3_PROTECTION','UNCERTAIN_RETAINED','RECONCILIATION_ONLY'],['E00-12','E00-11'],True,True),
('T13-F','LAB',['OWNER_POSTCHECK_MISSING'],['ENGINE','RECONCILIATION_ONLY'],['VERIFY_PROTECTION','RESUME_OR_RECONCILE'],[11,12,20],['C3_PROTECTION','DURABLE_WAIT'],['E00-12'],True,True),
('T13-G','LAB',['EXISTING_TARGET_PROTECTION'],['HOST_RESTART'],['VERIFY_PROTECTION','RUN_OWNER_LIFECYCLE'],[0,20],['C3_PROTECTION','LIFECYCLE_EPOCH'],['E00-12'],True,True),
# T14 exact
('T14-A','LAB',['QUALIFICATION_MISSING'],['ENTRY_ONLY'],['VERIFY_ENTRY_REJECTION'],[11],['ENTRY_GATE','QUALIFICATION_SCOPE'],['E00-13'],False,True),
('T14-B','LAB',['QUALIFICATION_INVALID'],['ENTRY_ONLY'],['VERIFY_ENTRY_REJECTION'],[11],['ENTRY_GATE','QUALIFICATION_SCOPE'],['E00-13'],False,True),
('T14-C','LAB',['QUALIFICATION_MISMATCH'],['ENTRY_ONLY'],['VERIFY_ENTRY_REJECTION'],[16],['ENTRY_GATE','QUALIFICATION_SCOPE'],['E00-13'],False,True),
('T14-D','LAB',['TRUST_FORGERY'],['ENTRY_ONLY'],['VERIFY_ENTRY_REJECTION'],[12,15],['ENTRY_GATE','EXPECTED_REJECTION'],['E00-10','E00-13'],False,True),
('T14-E','LAB',['REGISTERED_DISPOSABLE_LAB'],['CREATE'],['INVOKE_PRODUCTION_REQUEST'],[0],['ENTRY_GATE','CREATE_ROUTE'],['E00-10'],True,True),
('T14-F','LAB',['SITE_FAKE_LAB'],['ENTRY_ONLY'],['VERIFY_ENTRY_REJECTION'],[12],['ENTRY_GATE','EXPECTED_REJECTION'],['E00-10'],False,True),
('T14-G','LAB',['DISCOVERY_UNKNOWN_GUEST'],['DISCOVERY'],['INVOKE_PRODUCTION_REQUEST'],[0,11,16,20],['ENTRY_GATE','PASSIVE_NO_LAUNCH'],['E00-04','E00-13'],False,True),
('T14-H','LAB',['ENGINE_ABSENT_PROFILE'],['ENGINE'],['INVOKE_PRODUCTION_REQUEST'],[0,20],['ENTRY_GATE','C3_PROTECTION'],['E00-02','E00-13'],True,True),
('T14-I','LAB',['APPROVAL_EXPIRES_ON_RESUME'],['ENGINE','RECONCILIATION_ONLY'],['INVOKE_PRODUCTION_REQUEST','RESUME_OR_RECONCILE'],[12,20],['DURABLE_WAIT','NO_DUPLICATE_MUTATION'],['E00-11'],True,True),
]

PROCEDURES={row[0]:P(row[0],row[1],row[2],row[3],row[4],row[5],row[6],row[7],destructive=row[8],native=row[9]) for row in _ROWS}
require(len(PROCEDURES)==len(_ROWS),15,'HARNESS_DUPLICATE_CASE')

def case_ids():return tuple(PROCEDURES)
def procedure(case_id):
    require(case_id in PROCEDURES,10,'HARNESS_CASE_UNKNOWN');return PROCEDURES[case_id]

def validate_inventory(case_ids_from_inventory):
    actual=tuple(case_ids_from_inventory);require(len(actual)==len(set(actual)),15,'HARNESS_INVENTORY_DUPLICATE')
    require(set(actual)==set(PROCEDURES),15,'HARNESS_INVENTORY_COVERAGE')
    return True
